# Site
title:              Herrj1
bio:                'I am a technologist and computer scientist with interdisciplinary interests.'
description:        "Jekyll version of the Massively theme by HTML5UP"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://herrj1.github.io" # the base hostname & protocol for your site
background_image:   /images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
formspree_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author: herrj1

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   herrj1

# Social
analytics-id:       herrj1
twitter:            "#"
facebook:           "#"
instagram:          "#"
github:             herrj1

# personal
location:           FL, US
phone:              000-000-0000
email:              technologiesanalyst@gmail.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://herrj1.github.io/

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
